apiVersion: batch/v1
kind: Job
metadata:
  name: sdet-test-job
spec:
  template:
    spec:
      containers:
      - name: sdet-test
        image: sdet-test:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: test-reports
          mountPath: /app/target/surefire-reports
        - name: dshm
          mountPath: /dev/shm
      restartPolicy: Never
      volumes:
      - name: test-reports
        hostPath:
          path: /tmp/surefire-reports
          type: DirectoryOrCreate
      - name: dshm
        emptyDir:
          medium: Memory
  backoffLimit: 0