apiVersion: batch/v1
kind: Job
metadata:
  name: sdet-test-job
spec:
  template:
    spec:
      containers:
      - name: sdet-test
        image: docker.io/library/sdet-test:latest
        imagePullPolicy: Never
        volumeMounts:
        - name: test-reports
          mountPath: /app/target/surefire-reports
      restartPolicy: Never
      volumes:
      - name: test-reports
        hostPath:
          path: /tmp/surefire-reports
          type: DirectoryOrCreate
  backoffLimit: 0